# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version '>= 1.6.5'

unless Vagrant.has_plugin?('nugrant')
  warn "[\e[1m\e[31mERROR\e[0m]: Please run: vagrant plugin install nugrant"
  exit -1
end

BRIDGE_NETWORK = '10.2.0.10'
BRIDGE_NETMASK = '255.255.0.0'

def setup_defaults()
  {
    'box' => {
      'memory' => '2048',
      'cpus' => '2'
    }
  }
end

Vagrant.configure(2) do |config|

  config.user.defaults = setup_defaults

  config.vm.define 'hadoop-host', {:primary => true} do |dh|

    dh.vm.box = 'ubuntu/trusty64'
    dh.vm.synced_folder '.', '/hadoop-host', :disabled => false
    dh.vm.synced_folder '../hadoop-ops', '/hadoop-ops', :disabled => false

    dh.vm.network :private_network, :ip => BRIDGE_NETWORK, :netmask => BRIDGE_NETMASK

    dh.vm.network "forwarded_port", :guest => 8030, :host => 8030 # start-yarn.sh
    dh.vm.network "forwarded_port", :guest => 8031, :host => 8031 # start-yarn.sh
    dh.vm.network "forwarded_port", :guest => 8032, :host => 8032 # start-yarn.sh
    dh.vm.network "forwarded_port", :guest => 8033, :host => 8033 # start-yarn.sh

    dh.vm.network "forwarded_port", :guest => 8040, :host => 8040 # start-yarn.sh
    dh.vm.network "forwarded_port", :guest => 8042, :host => 8042 # start-yarn.sh
    dh.vm.network "forwarded_port", :guest => 8088, :host => 8088 # start-yarn.sh

    dh.vm.network "forwarded_port", :guest => 9000, :host => 9000 # start-dfs.sh

    dh.vm.network "forwarded_port", :guest => 50010, :host => 50010 # start-dfs.sh
    dh.vm.network "forwarded_port", :guest => 50020, :host => 50020 # start-dfs.sh
    dh.vm.network "forwarded_port", :guest => 50070, :host => 50070 # start-dfs.sh
    dh.vm.network "forwarded_port", :guest => 50075, :host => 50075 # start-dfs.sh
    dh.vm.network "forwarded_port", :guest => 50090, :host => 50090 # start-dfs.sh


    dh.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.memory = config.user.box.memory
      vb.cpus = config.user.box.cpus
    end
  end

  config.vm.provision 'shell', :inline =>
    "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

  config.vm.provision "shell", path: "provision.sh"

end

