# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version '>= 1.6.5'

unless Vagrant.has_plugin?('nugrant')
  warn "[\e[1m\e[31mERROR\e[0m]: Please run: vagrant plugin install nugrant"
  exit -1
end

BRIDGE_NETWORK = '10.1.0.100'
BRIDGE_NETMASK = '255.255.0.0'

def setup_defaults()
  {
    'box' => {
      'memory' => '1024',
      'cpus' => '1'
    }
  }
end

Vagrant.configure(2) do |config|

  config.user.defaults = setup_defaults

  config.vm.define 'redis-host', {:primary => true} do |dh|

    dh.vm.box = 'ubuntu/trusty64'
    dh.vm.hostname = 'master'
    dh.vm.synced_folder '.', '/redis-host', :disabled => false
    dh.vm.synced_folder '../redis-ops', '/redis-ops', :disabled => false
    dh.vm.synced_folder '../redis-app', '/redis-app', :disabled => false

    dh.vm.network :private_network, :ip => BRIDGE_NETWORK, :netmask => BRIDGE_NETMASK

    dh.vm.network "forwarded_port", :guest => 6379, :host => 6379 #
    dh.vm.network "forwarded_port", :guest => 8081, :host => 8081 #

    dh.vm.provider :virtualbox do |vb|
      vb.name = 'Redis host'
      vb.memory = config.user.box.memory
      vb.cpus = config.user.box.cpus
      vb.customize ["modifyvm", :id, "--groups", "/Big-Data-Training", "--nicpromisc2", "allow-all"]
    end
  end

  config.vm.provision 'shell', :inline =>
    "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

  config.vm.provision "shell", path: "provision.sh"

end
